version: '3.8'

services:
  tixie-pdv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_WEBHOOK_EVENTOS: ${NEXT_PUBLIC_WEBHOOK_EVENTOS}
        NEXT_PUBLIC_WEBHOOK_INGRESSOS: ${NEXT_PUBLIC_WEBHOOK_INGRESSOS}
        NEXT_PUBLIC_WEBHOOK_CLIENTE: ${NEXT_PUBLIC_WEBHOOK_CLIENTE}
        NEXT_PUBLIC_WEBHOOK_EMISSAO: ${NEXT_PUBLIC_WEBHOOK_EMISSAO}
        NEXT_PUBLIC_WEBHOOK_PDF_STATUS: ${NEXT_PUBLIC_WEBHOOK_PDF_STATUS}
    image: tixie-pdv:latest
    container_name: tixie-pdv
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_WEBHOOK_EVENTOS=${NEXT_PUBLIC_WEBHOOK_EVENTOS}
      - NEXT_PUBLIC_WEBHOOK_INGRESSOS=${NEXT_PUBLIC_WEBHOOK_INGRESSOS}
      - NEXT_PUBLIC_WEBHOOK_CLIENTE=${NEXT_PUBLIC_WEBHOOK_CLIENTE}
      - NEXT_PUBLIC_WEBHOOK_EMISSAO=${NEXT_PUBLIC_WEBHOOK_EMISSAO}
      - NEXT_PUBLIC_WEBHOOK_PDF_STATUS=${NEXT_PUBLIC_WEBHOOK_PDF_STATUS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - /app/node_modules
      - /app/.next 