-- Script para recriar a tabela user_empresas
-- Esta tabela faz a associação entre usuários e empresas

-- Criar a tabela user_empresas
CREATE TABLE IF NOT EXISTS user_empresas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  empresa_id BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Garantir que cada usuário só possa ser associado uma vez a cada empresa
  UNIQUE(user_id, empresa_id)
);

-- Adicionar comentários na tabela e colunas para documentação
COMMENT ON TABLE user_empresas IS 'Tabela de associação entre usuários e empresas';
COMMENT ON COLUMN user_empresas.id IS 'ID único da associação';
COMMENT ON COLUMN user_empresas.user_id IS 'ID do usuário no sistema de autenticação';
COMMENT ON COLUMN user_empresas.empresa_id IS 'ID da empresa';
COMMENT ON COLUMN user_empresas.created_at IS 'Data e hora de criação do registro';

-- Criar índices para otimizar consultas
CREATE INDEX IF NOT EXISTS idx_user_empresas_user_id ON user_empresas(user_id);
CREATE INDEX IF NOT EXISTS idx_user_empresas_empresa_id ON user_empresas(empresa_id);

-- Configurar políticas de segurança RLS (Row Level Security)
ALTER TABLE user_empresas ENABLE ROW LEVEL SECURITY;

-- Política para permitir que usuários vejam apenas suas próprias associações
CREATE POLICY user_empresas_select_policy ON user_empresas 
  FOR SELECT USING (auth.uid() = user_id OR auth.uid() IN (
    SELECT id FROM users WHERE is_super_admin = true
  ));

-- Política para permitir que apenas super admins insiram novas associações
CREATE POLICY user_empresas_insert_policy ON user_empresas 
  FOR INSERT WITH CHECK (auth.uid() IN (
    SELECT id FROM users WHERE is_super_admin = true
  ));

-- Política para permitir que apenas super admins alterem associações
CREATE POLICY user_empresas_update_policy ON user_empresas 
  FOR UPDATE USING (auth.uid() IN (
    SELECT id FROM users WHERE is_super_admin = true
  ));

-- Política para permitir que apenas super admins excluam associações
CREATE POLICY user_empresas_delete_policy ON user_empresas 
  FOR DELETE USING (auth.uid() IN (
    SELECT id FROM users WHERE is_super_admin = true
  )); 