-- Script simplificado para recriar a tabela user_empresas
-- Esta tabela faz a associação entre usuários e empresas

-- Criar a tabela user_empresas
CREATE TABLE IF NOT EXISTS user_empresas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  empresa_id BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Garantir que cada usuário só possa ser associado uma vez a cada empresa
  UNIQUE(user_id, empresa_id)
);

-- Criar índices para otimizar consultas
CREATE INDEX IF NOT EXISTS idx_user_empresas_user_id ON user_empresas(user_id);
CREATE INDEX IF NOT EXISTS idx_user_empresas_empresa_id ON user_empresas(empresa_id); 